"""Django settings for h4kslanding project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config

#from dotenv import load_dotenv, find_dotenv, dotenv_values
#dotenv_values(dotenv_path=None)
#load_dotenv(find_dotenv())
# update secret
#SECRET_KEY = os.environ['SECRET_KEY'] # replacement for actual key

SECRET_KEY = config('SECRET_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Logto Configuration
LOGTO_ENDPOINT = config('LOGTO_ENDPOINT', default='https://auth.h4ks.com')
LOGTO_M2M_CLIENT_ID = config('LOGTO_M2M_CLIENT_ID', default='')
LOGTO_M2M_CLIENT_SECRET = config('LOGTO_M2M_CLIENT_SECRET', default='')
LOGTO_APP_ID = config('LOGTO_APP_ID', default='')
LOGTO_APP_SECRET = config('LOGTO_APP_SECRET', default='')
LOGTO_REDIRECT_URI = config('LOGTO_REDIRECT_URI', default='https://h4ks.com/auth/callback')

STALWART_API_URL      = config('STALWART_API_URL',      default='https://mail.h4ks.com/api')
STALWART_ADMIN_USER   = config('STALWART_ADMIN_USER',   default='admin')
STALWART_ADMIN_SECRET = config('STALWART_ADMIN_SECRET', default='')

TURNSTILE_SITE_KEY   = config('TURNSTILE_SITE_KEY',   default='')
TURNSTILE_SECRET_KEY = config('TURNSTILE_SECRET_KEY', default='')

SHOW_NAV = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

#ALLOWED_HOSTS = ['h4ks.com',]
ALLOWED_HOSTS = ['*',]
CSRF_TRUSTED_ORIGINS = ['https://h4ks.com']

# Application definition

INSTALLED_APPS = [
    'webapp.apps.WebappConfig',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mozilla_django_oidc.middleware.SessionRefresh',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'h4kslanding.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'webapp.context_processors.ui_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'h4kslanding.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'data' / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_ROOT = '/static'
STATIC_ROOT = "static"

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

#STATIC_FILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
#]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL='/accounts/login'
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'webapp.auth.LogtoOIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

OIDC_RP_CLIENT_ID = config('LOGTO_APP_ID')
OIDC_RP_CLIENT_SECRET = config('LOGTO_APP_SECRET', default='')
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{config('LOGTO_ENDPOINT')}/oidc/auth"
OIDC_OP_TOKEN_ENDPOINT = f"{config('LOGTO_ENDPOINT')}/oidc/token"
OIDC_OP_USER_ENDPOINT = f"{config('LOGTO_ENDPOINT')}/oidc/me"
OIDC_OP_JWKS_ENDPOINT = f"{config('LOGTO_ENDPOINT')}/oidc/jwks"
OIDC_OP_LOGOUT_URL_METHOD = 'webapp.auth.provider_logout'
OIDC_RP_SIGN_ALGO = 'ES384'
OIDC_RP_SCOPES = 'openid profile email'
