# Generated by Django 5.0.7 on 2025-11-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_pendinguser_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User's preferred timezone (e.g., America/New_York)",
                max_length=64,
            ),
        ),
    ]
