# Generated by Django 5.0.7 on 2026-04-05 18:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_featuredproject_github_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=[
                    ("#5c9eff", "Blue"),
                    ("#ff8c4b", "Orange"),
                    ("#4ade80", "Green"),
                    ("#a371f7", "Purple"),
                    ("#f7cc71", "Yellow"),
                    ("#e05c5c", "Red"),
                    ("#5865f2", "Blurple"),
                    ("#58a6a0", "Teal"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="featuredproject",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="",
                image_field=None,
                max_length=25,
                samples=[
                    ("#5c9eff", "Blue"),
                    ("#ff8c4b", "Orange"),
                    ("#4ade80", "Green"),
                    ("#a371f7", "Purple"),
                    ("#f7cc71", "Yellow"),
                    ("#e05c5c", "Red"),
                    ("#5865f2", "Blurple"),
                    ("#58a6a0", "Teal"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=25,
                null=True,
                samples=[
                    ("#5c9eff", "Blue"),
                    ("#ff8c4b", "Orange"),
                    ("#4ade80", "Green"),
                    ("#a371f7", "Purple"),
                    ("#f7cc71", "Yellow"),
                    ("#e05c5c", "Red"),
                    ("#5865f2", "Blurple"),
                    ("#58a6a0", "Teal"),
                ],
            ),
        ),
    ]
